import { Product, ProductCategory } from '../../core/models/product.model';

export const MOCK_MODE = false;

export const MOCK_RAW_CATEGORIES: ProductCategory[] = [
  {
    id: '1',
    category_hu: 'Gyógyszerek',
    category_en: 'Medicines',
    category_de: 'Medikamente',
    emoji: '💊',
    color: '#e74c3c',
    number_of_products: '3',
  },
  {
    id: '2',
    category_hu: 'Természetes szerek',
    category_en: 'Natural Remedies',
    category_de: 'Naturheilmittel',
    emoji: '🌿',
    color: '#27ae60',
    number_of_products: '2',
  },
  {
    id: '3',
    category_hu: 'Baba & Mama',
    category_en: 'Baby & Mother',
    category_de: 'Baby & Mutter',
    emoji: '🍼',
    color: '#3498db',
    number_of_products: '1',
  },
  {
    id: '4',
    category_hu: 'Egészséges életmód',
    category_en: 'Healthy Lifestyle',
    category_de: 'Gesunder Lifestyle',
    emoji: '🏃',
    color: '#f39c12',
    number_of_products: '2',
  },
  {
    id: '5',
    category_hu: 'Szezonális egészség',
    category_en: 'Seasonal Health',
    category_de: 'Saisongesundheit',
    emoji: '🌡️',
    color: '#9b59b6',
    number_of_products: '1',
  },
];

export const MOCK_RAW_PRODUCTS: Product[] = [
  {
    id: '1',
    name: 'Algoflex Forte 400mg',
    name_hu: 'Algoflex Forte 400mg',
    name_en: 'Algoflex Forte 400mg',
    name_de: 'Algoflex Forte 400mg',
    description_hu:
      'Fájdalomcsillapító és gyulladáscsökkentő hatású ibuprofén tartalmú filmtabletta. Fejfájás, fogfájás, hátfájás, ízületi fájdalmak esetén alkalmazható.',
    description_en:
      'Ibuprofen-based film-coated tablet with analgesic and anti-inflammatory effect. For headache, toothache, back pain and joint pain.',
    description_de:
      'Ibuprofen-haltige Filmtablette mit schmerzstillender und entzündungshemmender Wirkung.',
    description_preview_hu: 'Hatékony fájdalomcsillapítás ibuprofénnel.',
    description_preview_en: 'Effective pain relief with ibuprofen.',
    description_preview_de: 'Effektive Schmerzlinderung mit Ibuprofen.',
    price_huf: '2490',
    price_usd: '6.99',
    price_eur: '6.49',
    sale_percentage: '0',
    stock: '142',
    times_ordered: '541',
    category_id: '1',
    category: '1',
    manufacturer: 'TEVA Gyógyszergyár Zrt.',
    brand: 'Algoflex',
    rating: '4.6',
    sku: 'ALG-400-24',
    active_ingredients: 'Ibuprofenum 400mg',
    packaging_hu: '24 filmtabletta',
    packaging_en: '24 film-coated tablets',
    packaging_de: '24 Filmtabletten',
    thumbnail_url: 'assets/products/1/1.webp',
    featured: '1',
    created_at: '2024-01-15T10:00:00Z',
    updated_at: '2025-01-15T10:00:00Z',
  },
  {
    id: '2',
    name: 'Nurofen Express 200mg',
    name_hu: 'Nurofen Express 200mg',
    name_en: 'Nurofen Express 200mg',
    name_de: 'Nurofen Express 200mg',
    description_hu:
      'Gyorsan ható ibuprofen kapszula. Szabad szemmel nem látható ibuprofen-nátrium hatóanyag gyorsabb felszívódást biztosít.',
    description_en: 'Fast-acting ibuprofen capsule. Ibuprofen sodium provides faster absorption.',
    description_de:
      'Schnell wirkendes Ibuprofen-Kapsel mit Ibuprofen-Natrium für schnellere Aufnahme.',
    description_preview_hu: 'Gyorsabb hatás ibuprofen-nátriummal.',
    description_preview_en: 'Faster effect with ibuprofen sodium.',
    description_preview_de: 'Schnellere Wirkung mit Ibuprofen-Natrium.',
    price_huf: '1890',
    price_usd: '5.29',
    price_eur: '4.89',
    sale_percentage: '15',
    stock: '7',
    times_ordered: '312',
    category_id: '1',
    category: '1',
    manufacturer: 'Reckitt Benckiser',
    brand: 'Nurofen',
    rating: '4.3',
    sku: 'NUR-200-12',
    active_ingredients: 'Ibuprofen-natrium 342mg (= Ibuprofen 200mg)',
    packaging_hu: '12 kapszula',
    packaging_en: '12 capsules',
    packaging_de: '12 Kapseln',
    thumbnail_url: 'assets/products/2/1.webp',
    featured: '0',
    created_at: '2024-02-01T10:00:00Z',
    updated_at: '2025-02-01T10:00:00Z',
  },
  {
    id: '3',
    name: 'Béres C-vitamin 1000mg',
    name_hu: 'Béres C-vitamin 1000mg',
    name_en: 'Béres Vitamin C 1000mg',
    name_de: 'Béres Vitamin C 1000mg',
    description_hu:
      'Magas dózisú C-vitamin pezsgőtabletta. Erős antioxidáns hatással támogatja az immunrendszert és csökkenti a fáradtság érzetét.',
    description_en:
      'High-dose vitamin C effervescent tablet. Strong antioxidant effect supports the immune system and reduces fatigue.',
    description_de:
      'Hochdosierte Vitamin C Brausetablette. Starke antioxidative Wirkung unterstützt das Immunsystem.',
    description_preview_hu: 'Immunerősítő, antioxidáns C-vitamin.',
    description_preview_en: 'Immune-boosting, antioxidant vitamin C.',
    description_preview_de: 'Immunstärkendes, antioxidatives Vitamin C.',
    price_huf: '3490',
    price_usd: '9.79',
    price_eur: '9.09',
    sale_percentage: '0',
    stock: '88',
    times_ordered: '267',
    category_id: '2',
    category: '2',
    manufacturer: 'Béres Pharmaceuticals',
    brand: 'Béres',
    rating: '4.8',
    sku: 'BER-CVT-60',
    active_ingredients: 'Acidum ascorbicum 1000mg',
    packaging_hu: '20 pezsgőtabletta',
    packaging_en: '20 effervescent tablets',
    packaging_de: '20 Brausetablette',
    thumbnail_url: 'assets/products/3/1.webp',
    featured: '1',
    created_at: '2024-03-01T10:00:00Z',
    updated_at: '2025-03-01T10:00:00Z',
  },
  {
    id: '4',
    name: 'Pampers Active Baby 3-as',
    name_hu: 'Pampers Active Baby 3-as méret',
    name_en: 'Pampers Active Baby Size 3',
    name_de: 'Pampers Active Baby Größe 3',
    description_hu:
      'Puha, légáteresztő pelenka 6-10 kg-os babáknak. Akár 12 órán át tartó szárazságot biztosít.',
    description_en:
      'Soft, breathable diaper for babies 6-10 kg. Provides dryness for up to 12 hours.',
    description_de:
      'Weiches, atmungsaktives Windel für Babys 6-10 kg. Bietet bis zu 12 Stunden Trockenheit.',
    description_preview_hu: '12 óra szárazság, 6-10 kg-os babáknak.',
    description_preview_en: '12 hours dryness, for babies 6-10 kg.',
    description_preview_de: '12 Stunden Trockenheit, für Babys 6-10 kg.',
    price_huf: '8990',
    price_usd: '25.29',
    price_eur: '23.49',
    sale_percentage: '0',
    stock: '0',
    times_ordered: '189',
    category_id: '3',
    category: '3',
    manufacturer: 'Procter & Gamble',
    brand: 'Pampers',
    rating: '4.7',
    sku: 'PAM-ACT-3-90',
    active_ingredients: '—',
    packaging_hu: '90 darab',
    packaging_en: '90 pieces',
    packaging_de: '90 Stück',
    thumbnail_url: 'assets/products/4/1.webp',
    featured: '0',
    created_at: '2024-04-01T10:00:00Z',
    updated_at: '2025-04-01T10:00:00Z',
  },
  {
    id: '5',
    name: 'Voltaren Emulgel 1%',
    name_hu: 'Voltaren Emulgel 1%',
    name_en: 'Voltaren Emulgel 1%',
    name_de: 'Voltaren Emulgel 1%',
    description_hu:
      'Diklofenák-dietilamint tartalmazó gél izom- és ízületi fájdalmakra. Mélyen behatol a szövetekbe.',
    description_en:
      'Diclofenac diethylamine gel for muscle and joint pain. Penetrates deeply into tissues.',
    description_de:
      'Diclofenac-Diethylamin-Gel bei Muskel- und Gelenkschmerzen. Dringt tief ins Gewebe ein.',
    description_preview_hu: 'Mélyen ható ízületi és izomfájdalom gél.',
    description_preview_en: 'Deep-acting joint and muscle pain gel.',
    description_preview_de: 'Tiefwirkendes Gelenk- und Muskelschmerzgel.',
    price_huf: '4290',
    price_usd: '12.09',
    price_eur: '11.19',
    sale_percentage: '20',
    stock: '34',
    times_ordered: '204',
    category_id: '1',
    category: '1',
    manufacturer: 'GlaxoSmithKline',
    brand: 'Voltaren',
    rating: '4.5',
    sku: 'VOL-EMU-100G',
    active_ingredients: 'Diclofenacum diethylaminum 11,6mg/g',
    packaging_hu: '100g gél',
    packaging_en: '100g gel',
    packaging_de: '100g Gel',
    thumbnail_url: 'assets/products/5/1.webp',
    featured: '1',
    created_at: '2024-05-01T10:00:00Z',
    updated_at: '2025-05-01T10:00:00Z',
  },
  {
    id: '6',
    name: 'Multi-vitamin komplex',
    name_hu: 'Multi-vitamin komplex',
    name_en: 'Multi-vitamin complex',
    name_de: 'Multi-Vitamin-Komplex',
    description_hu:
      '23 vitamint és ásványi anyagot tartalmazó komplex formula a napi tápanyagbevitel fedezéséhez.',
    description_en:
      'Complex formula containing 23 vitamins and minerals to cover daily nutrient intake.',
    description_de:
      'Komplexformel mit 23 Vitaminen und Mineralstoffen zur Deckung des täglichen Nährstoffbedarfs.',
    description_preview_hu: '23 vitamin és ásványi anyag egyben.',
    description_preview_en: '23 vitamins and minerals in one.',
    description_preview_de: '23 Vitamine und Mineralstoffe in einem.',
    price_huf: '5490',
    price_usd: '15.49',
    price_eur: '14.39',
    sale_percentage: '0',
    stock: '5',
    times_ordered: '143',
    category_id: '4',
    category: '4',
    manufacturer: 'Béres Pharmaceuticals',
    brand: 'Béres',
    rating: '4.2',
    sku: 'MUL-VIT-100',
    active_ingredients:
      'Vitamin A, B1, B2, B3, B5, B6, B7, B9, B12, C, D3, E, K1, Ca, Mg, Zn, Fe, Cu, Mn, Cr, Mo, Se, I',
    packaging_hu: '100 tabletta',
    packaging_en: '100 tablets',
    packaging_de: '100 Tabletten',
    thumbnail_url: 'assets/products/6/1.webp',
    featured: '0',
    created_at: '2024-06-01T10:00:00Z',
    updated_at: '2025-06-01T10:00:00Z',
  },
  {
    id: '7',
    name: 'Strepsils Citrom & Méz',
    name_hu: 'Strepsils Citrom & Méz szopogató tabletta',
    name_en: 'Strepsils Lemon & Honey lozenges',
    name_de: 'Strepsils Zitrone & Honig Lutschtabletten',
    description_hu:
      'Antibakteriális hatású szopogató tabletta torokfájásra. Citrom és méz ízű, kellemes íze van.',
    description_en: 'Antibacterial lozenge for sore throat. Pleasant lemon and honey flavour.',
    description_de:
      'Antibakteriell wirkende Lutschtablette bei Halsschmerzen. Angenehmer Zitronen-Honig-Geschmack.',
    description_preview_hu: 'Antibakteriális torokerősítő szopogató.',
    description_preview_en: 'Antibacterial throat-soothing lozenge.',
    description_preview_de: 'Antibakteriell lindernde Lutschtablette.',
    price_huf: '1290',
    price_usd: '3.59',
    price_eur: '3.29',
    sale_percentage: '0',
    stock: '210',
    times_ordered: '780',
    category_id: '5',
    category: '5',
    manufacturer: 'Reckitt Benckiser',
    brand: 'Strepsils',
    rating: '4.4',
    sku: 'STR-CIT-36',
    active_ingredients: 'Amylmetacresol 0.6mg, 2,4-Dichlorobenzyl alcohol 1.2mg',
    packaging_hu: '36 szopogató tabletta',
    packaging_en: '36 Sucking Tablet',
    packaging_de: '36 Tabletten zum Aufsaugen',
    thumbnail_url: 'assets/products/7/1.webp',
    featured: '1',
    created_at: '2024-07-01T10:00:00Z',
    updated_at: '2025-07-01T10:00:00Z',
  },
  {
    id: '8',
    name: 'Omega-3 halolaj 1000mg',
    name_hu: 'Omega-3 halolaj 1000mg',
    name_en: 'Omega-3 Fish Oil 1000mg',
    name_de: 'Omega-3 Fischöl 1000mg',
    description_hu:
      'Magas EPA és DHA tartalmú halolaj kapszula. Szív- és érrendszeri egészséghez, agyműködés és látás támogatásához.',
    description_en:
      'High EPA and DHA fish oil capsule. For cardiovascular health, brain function and vision support.',
    description_de:
      'Hochdosierte EPA- und DHA-Fischölkapsel für Herz-Kreislauf-Gesundheit, Gehirnfunktion und Sehvermögen.',
    description_preview_hu: 'Szív, agy és látás: EPA + DHA komplex.',
    description_preview_en: 'Heart, brain and vision: EPA + DHA complex.',
    description_preview_de: 'Herz, Gehirn und Sehen: EPA + DHA Komplex.',
    price_huf: '4290',
    price_usd: '12.09',
    price_eur: '11.19',
    sale_percentage: '0',
    stock: '67',
    times_ordered: '298',
    category_id: '4',
    category: '4',
    manufacturer: 'Now Foods',
    brand: "Roy's Natural",
    rating: '4.6',
    sku: 'OM3-90',
    active_ingredients: 'EPA 360mg, DHA 240mg per kapszula',
    packaging_hu: '90 kapszula',
    packaging_en: '90 capsules',
    packaging_de: '90 Kapseln',
    thumbnail_url: 'assets/products/8/1.webp',
    featured: '0',
    created_at: '2024-08-01T10:00:00Z',
    updated_at: '2025-08-01T10:00:00Z',
  },
  {
    id: '9',
    name: 'Kamilla tea bio',
    name_hu: 'Kamilla tea bio',
    name_en: 'Organic chamomile tea',
    name_de: 'Bio Kamillentee',
    description_hu:
      'Prémium bio kamilla virágzat tea. Természetes nyugtató, gyulladáscsökkentő és emésztést segítő hatással.',
    description_en:
      'Premium organic chamomile flower tea. Natural calming, anti-inflammatory and digestive aid.',
    description_de:
      'Hochwertiger Bio-Kamillenblütentee. Natürlich beruhigend, entzündungshemmend und verdauungsfördernd.',
    description_preview_hu: 'Bio kamilla, természetes nyugtató és emésztéssegítő.',
    description_preview_en: 'Organic chamomile, natural calming and digestive aid.',
    description_preview_de: 'Bio-Kamille, natürlich beruhigend und verdauungsfördernd.',
    price_huf: '1490',
    price_usd: '4.19',
    price_eur: '3.89',
    sale_percentage: '0',
    stock: '180',
    times_ordered: '156',
    category_id: '2',
    category: '2',
    manufacturer: 'HerbalLife Kft.',
    brand: "Roy's Herbs",
    rating: '4.3',
    sku: 'TEA-CAM-20',
    active_ingredients: 'Matricaria chamomilla flos 100%',
    packaging_hu: '20 filter',
    packaging_en: '20 filter',
    packaging_de: '20 Filter',
    thumbnail_url: 'assets/products/9/1.webp',
    featured: '0',
    created_at: '2024-09-01T10:00:00Z',
    updated_at: '2025-09-01T10:00:00Z',
  },
  {
    id: '10',
    name: 'D3 + K2 vitamin 2000 IU',
    name_hu: 'D3 + K2 vitamin 2000 IU',
    name_en: 'Vitamin D3 + K2 2000 IU',
    name_de: 'Vitamin D3 + K2 2000 IE',
    description_hu:
      'D3 és K2 vitamin kombinációja. A D3 kalcium felszívódást segít, a K2 gondoskodik a helyes elhelyezkedéséről a csontokban.',
    description_en:
      'Combination of D3 and K2 vitamins. D3 supports calcium absorption, K2 ensures it goes to the bones.',
    description_de:
      'Kombination aus D3- und K2-Vitamin. D3 unterstützt die Kalziumaufnahme, K2 sorgt für die richtige Einlagerung in den Knochen.',
    description_preview_hu: 'D3 + K2: kalcium a csontoknak, immunerő.',
    description_preview_en: 'D3 + K2: calcium for bones, immune strength.',
    description_preview_de: 'D3 + K2: Kalzium für Knochen, Immunstärke.',
    price_huf: '3990',
    price_usd: '11.19',
    price_eur: '10.39',
    sale_percentage: '10',
    stock: '52',
    times_ordered: '211',
    category_id: '2',
    category: '2',
    manufacturer: 'Vitabalans Oy',
    brand: "Roy's Premium",
    rating: '4.7',
    sku: 'D3K2-60',
    active_ingredients: 'Kolekalciferol 50mcg (2000IU), Menachinon-7 75mcg',
    packaging_hu: '60 kapszula',
    packaging_en: '60 capsules',
    packaging_de: '60 Kapseln',
    thumbnail_url: 'assets/products/10/1.webp',
    featured: '1',
    created_at: '2024-10-01T10:00:00Z',
    updated_at: '2025-10-01T10:00:00Z',
  },
];
