import { AdminUser, AdminOrder } from '../../core/services/account.service';
import { Post } from '../../core/models/forum.model';

export const MOCK_MODE = true;

export const MOCK_USERS: AdminUser[] = [
  {
    id: '1',
    email: 'kovacs.bela@gmail.com',
    first_name: 'Béla',
    last_name: 'Kovács',
    account_state: 'admin',
    created_at: '2024-01-15T10:23:00',
  },
  {
    id: '2',
    email: 'nagy.anna@outlook.com',
    first_name: 'Anna',
    last_name: 'Nagy',
    account_state: 'verified',
    created_at: '2024-02-03T08:11:00',
  },
  {
    id: '3',
    email: 'horvath.peter@freemail.hu',
    first_name: 'Péter',
    last_name: 'Horváth',
    account_state: 'verified',
    created_at: '2024-03-22T14:55:00',
  },
  {
    id: '4',
    email: 'toth.maria@citromail.hu',
    first_name: 'Mária',
    last_name: 'Tóth',
    account_state: 'unverified',
    created_at: '2024-04-10T09:30:00',
  },
  {
    id: '5',
    email: 'szabo.gabor@gmail.com',
    first_name: 'Gábor',
    last_name: 'Szabó',
    account_state: 'banned',
    created_at: '2024-04-18T16:42:00',
  },
  {
    id: '6',
    email: 'kiss.eva@yahoo.com',
    first_name: 'Éva',
    last_name: 'Kiss',
    account_state: 'verified',
    created_at: '2024-05-01T11:00:00',
  },
  {
    id: '7',
    email: 'fekete.laszlo@gmail.com',
    first_name: 'László',
    last_name: 'Fekete',
    account_state: 'deleted',
    created_at: '2024-05-15T07:18:00',
  },
  {
    id: '8',
    email: 'molnar.zsuzsa@gmail.com',
    first_name: 'Zsuzsa',
    last_name: 'Molnár',
    account_state: 'verified',
    created_at: '2024-06-02T13:27:00',
  },
];

export const MOCK_ORDERS: AdminOrder[] = [
  {
    id: '1001',
    user_id: '2',
    email: 'nagy.anna@outlook.com',
    billing_name: 'Nagy Anna',
    order_status: 'delivered',
    created_at: '2025-02-10T10:15:00',
    price: '12490',
    city: 'Budapest',
    zipcode: '1051',
    address: 'Váci utca',
    house_number: '14',
    apartment_number: '3',
    phone_number: '+36301234567',
    note: '',
  },
  {
    id: '1002',
    user_id: '3',
    email: 'horvath.peter@freemail.hu',
    billing_name: 'Horváth Péter',
    order_status: 'shipped',
    created_at: '2025-02-18T14:40:00',
    price: '7890',
    city: 'Pécs',
    zipcode: '7621',
    address: 'Király utca',
    house_number: '22',
    apartment_number: '',
    phone_number: '+36209876543',
    note: 'Kérem a csengőre nyomni: Horváth',
  },
  {
    id: '1003',
    user_id: '6',
    email: 'kiss.eva@yahoo.com',
    billing_name: 'Kiss Éva',
    order_status: 'processing',
    created_at: '2025-03-01T09:05:00',
    price: '24990',
    city: 'Debrecen',
    zipcode: '4024',
    address: 'Piac utca',
    house_number: '5',
    apartment_number: '2',
    phone_number: '+36701112233',
    note: '',
  },
  {
    id: '1004',
    user_id: '8',
    email: 'molnar.zsuzsa@gmail.com',
    billing_name: 'Molnár Zsuzsa',
    order_status: 'pending',
    created_at: '2025-03-10T17:30:00',
    price: '4990',
    city: 'Győr',
    zipcode: '9021',
    address: 'Baross Gábor út',
    house_number: '31',
    apartment_number: '',
    phone_number: '+36305559988',
    note: 'Munkaidőben kézbesítsék',
  },
  {
    id: '1005',
    user_id: '2',
    email: 'nagy.anna@outlook.com',
    billing_name: 'Nagy Anna',
    order_status: 'cancelled',
    created_at: '2025-03-12T11:00:00',
    price: '9800',
    city: 'Budapest',
    zipcode: '1051',
    address: 'Váci utca',
    house_number: '14',
    apartment_number: '3',
    phone_number: '+36301234567',
    note: 'Téves rendelés',
  },
  {
    id: '1006',
    user_id: '3',
    email: 'horvath.peter@freemail.hu',
    billing_name: 'Horváth Péter',
    order_status: 'delivered',
    created_at: '2025-03-14T08:22:00',
    price: '31500',
    city: 'Pécs',
    zipcode: '7621',
    address: 'Király utca',
    house_number: '22',
    apartment_number: '',
    phone_number: '+36209876543',
    note: '',
  },
  {
    id: '1007',
    user_id: '6',
    email: 'kiss.eva@yahoo.com',
    billing_name: 'Kiss Éva',
    order_status: 'shipped',
    created_at: '2025-03-16T15:10:00',
    price: '18200',
    city: 'Debrecen',
    zipcode: '4024',
    address: 'Piac utca',
    house_number: '5',
    apartment_number: '2',
    phone_number: '+36701112233',
    note: '',
  },
];

export const MOCK_POSTS: Post[] = [
  {
    id: '1',
    title: 'Tesztposzt – Vitaminok télen',
    slug: 'tesztposzt-vitaminok-telen',
    excerpt: 'Rövid összefoglaló a téli vitaminpótlásról.',
    content: '<p>Bővebb tartalom ide kerül...</p>',
    user_id: '1',
    category_id: '1',
    tags: 'vitamin,tél,immunrendszer',
    image_url: '',
    status: 'published',
    views: 120,
    likes: 14,
    comment_count: 3,
    is_featured: 1,
    created_at: '2026-03-01T10:00:00',
    updated_at: '2026-03-01T10:00:00',
    published_at: '2026-03-01T10:00:00',
  },
  {
    id: '2',
    title: 'Draft cikk – Vérnyomás és életmód',
    slug: 'draft-cikk-vernyomas-es-eletmod',
    excerpt: 'Draft poszt, még nem publikált.',
    content: '<p>Tartalom írás alatt...</p>',
    user_id: '1',
    category_id: '2',
    tags: 'vérnyomás,egészség',
    image_url: '',
    status: 'draft',
    views: 0,
    likes: 0,
    comment_count: 0,
    is_featured: 0,
    created_at: '2026-03-15T09:00:00',
    updated_at: '2026-03-15T09:00:00',
  },
  {
    id: '3',
    title: 'Rejtett poszt – Szezális egészség',
    slug: 'rejtett-poszt-szezonalis-egeszseg',
    excerpt: 'Hidden státuszú bejegyzés.',
    content: '<p>Ez a poszt rejtett.</p>',
    user_id: '1',
    category_id: '3',
    tags: 'szezonális',
    image_url: '',
    status: 'hidden',
    views: 5,
    likes: 0,
    comment_count: 0,
    is_featured: 0,
    created_at: '2026-03-20T12:00:00',
    updated_at: '2026-03-20T12:00:00',
  },
];
