export const ICONS = {
  user: 'assets/icons/userwhite.png',
  support: 'assets/icons/supportwhite.png',
  basket: 'assets/icons/basketwhite.png',
  buy: 'assets/icons/buywhite.png',
  add: 'assets/icons/add.png',
  location: 'assets/icons/locationwhite.png',
  dropdown: 'assets/icons/dropdownwhite.png',
  english: 'assets/icons/english.png',
  hungary: 'assets/icons/hungary.png',
  info: 'assets/icons/infogreen.png',
  instagram: 'assets/icons/instagramwhite.png',
  customers: 'assets/icons/customerswhite.png',
  delete: 'assets/icons/deletegreen.png',
  ship: 'assets/icons/shipwhite.png',
  x: 'assets/icons/xwhite.png',
  facebook: 'assets/icons/facebookwhite.png',
  sort: 'assets/icons/sortwhite.png',
  sale: 'assets/icons/salewhite.png',
  report: 'assets/icons/reportwhite.png',
  select: 'assets/icons/selectgreen.png',
  remove: 'assets/icons/remove.png',
  share: 'assets/icons/sharegreen.png',
  rename: 'assets/icons/rename.png',
  phone: 'assets/icons/phonegreen.png',
  payment: 'assets/icons/paymentgreen.png',
  order: 'assets/icons/ordergreen.png',
  mail: 'assets/icons/mailwhite.png',
  login: 'assets/icons/logingreen.png',
  language: 'assets/icons/languagegreen.png',
  filter: 'assets/icons/filterwhite.png',
  favorites: 'assets/icons/favoriteswhite.png',
  calendar: 'assets/icons/calendarwhite.png',
};

export const IMAGES = {
  logo: 'assets/images/ROYS_SHACK_WHITE.png',
};
